# Generated by Django 6.0 on 2026-04-02 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('relationship_start_date', models.DateTimeField(blank=True, null=True)),
                ('relationship_stage', models.CharField(blank=True, choices=[('EXPLORATION', 'Exploration'), ('DATING', 'Dating'), ('ENGAGED', 'Engaged'), ('MARRIED', 'Married'), ('REKINDLED', 'Rekindled')], max_length=20, null=True)),
                ('relationship_goal', models.TextField(blank=True, null=True)),
                ('invite_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
